#!/bin/bash
#
#  Run sample programs of jsfj4
#

# Run Jupiter in JSF environment
# Jupiter initialization script is defined in a file, rungun.mac,
# which generate mu+ a single track event.
#
jsf -b -q --maxevt=3 --g4macro=rungun.mac gui.C 

# read the Jupiter result of privious run, which is stored in the file
# jsfj4.root
jsf -b -q -conf=read.conf gui.C

# Run Jupiter in JSF environment
# Using the Pythia Generator inplemented in jsf
jsf -b -q --maxevt=3 --generator=0 gui.C

# Run Jupiter in JSF environment
# without VTX package
jsf -b -q --maxevt=3 --hasvtx=0  gui.C

