#!/bin/csh
#
#  To initiate allrun script.
#

set typeos=`uname`
if ( $typeos == "HI-UX" ) then
   set destdir="/:/w/30/miyamoto/simdst/sample"
else
   set destdir="/home/miyamoto/simdst/i386"
endif
if( `logname` != "miyamoto" ) destdir="./"

set dstr=`date +%y%m%d`
./allrun $destdir >&! $destdir/jobout.allrun.$dstr &

exit
