#!/bin/bash

# ---------------------------------------------
has_CLHEP()
{
  clheplib=/usr/lib
  if [ "X$CLHEP_BASE_DIR" != "X" ] ; then
    clheplib=$CLHEP_BASE_DIR/lib
  fi
  if [ -a $clheplib/libCLHEP.a ] ; then
#    echo $clheplib/libCLHEP.a
    echo yes
    exit 0
  fi
  exit -1
}

# ---------------------------------------------
has_LEDA()
{
  if [ "X$LEDAROOT" == "X" ] ; then
    exit -1
  fi
  if [ ! -e $LEDAROOT/lib/libAnlib.so ] ; then
    exit -1
  fi
  if [ ! -e $LEDAROOT/include ] ; then
    exit -1
  fi
  echo "yes"
  exit 0
}
# ---------------------------------------------
has_STDHEP()
{
  if [ "X$STDHEPDIR" == "X" ] ; then
    exit -1
  fi
  echo "yes"
  exit 0
}

# ---------------------------------------------
has_Anlib()
{
  if [ "X$ANLIBROOT" == "X" ] ; then
    exit -1
  fi
  if [ ! -e $ANLIBROOT/lib/libAnlib.so ] ; then
    exit -1
  fi
  if [ ! -e $ANLIBROOT/include ] ; then
    exit -1
  fi

#  echo $ANLIBROOT/include
  echo yes
  exit 0

}
# ---------------------------------------------
has_LCIO()
{
  if [ "X$LCIO" == "X" ] ; then
    exit -1
  fi
  if [ ! -e $LCIO/lib/liblcio.a -a ! -e $LCIO/lib/liblcio.so ] ; then
    exit -1
  fi
  if [ ! -e $LCIO/sio/lib/libsio.a ! -e $LCIO/lib/libsio.so ] ; then
    exit -1
  fi

  echo yes
  exit 0

}


# ---------------------------------------------
print_help()
{
cat <<EOF
 opts-config [options]
 options = --has_CLHEP --has_Anlib --has_LCIO --has_LEDA --has__STDHEP --help
EOF
}

# ---------------------------------------------
while [ $# -ne 0 ] 
do 
  case "$1" in 
    --has_CLHEP) has_CLHEP ;;
    --has_Anlib) has_Anlib ;;
    --has_LCIO)  has_LCIO ;;
    --has_LEDA)  has_LEDA ;;
    --has_STDHEP)  has_STDHEP ;;
    *) print_help ;;
  esac
  shift
done

