#!/bin/sh
#
# Run JIM simulation
#

helpmsg()
{

cat <<EOF
runmain [options]

Run jim simulator

Valid options are
  -pid n    : Particle ID to generate
  -smear    : Use smearing simulator
  -full     : Use full simulator
  -out fn   : output file name
  -b        : no graphics
  -numevt n : Number of events to generate
  -nump n   : Number of particle per event
  -hdecay n : Select H decay mode (0=all,1=bb, 2=cc, 3=gg)
  -cylvtx   : Use cylindrical VTX geometry
EOF
}

#
#  Default values
#
execfile="$JLCSIMROOT/bin/jim"
echo "Exec file is $execfile"
optfull="#"
optfull="SIMD 3=1 4=1 11=1 12=1"
numevt=3
out="/dev/null"
graphic=1
swopt=" 0  0 "
dbgopt="#"
igvx="#"

while [ $# -ne 0 ] 
do
 case "$1" in
  -pid) shift ;  pid=$1 ;;
  -smear) optfull="SIMD 3=1 4=1 11=1 12=1" ;;
  -full) optfull="SIMD 3=0 4=0 11=1 12=1" ;;
  -numevt) shift ; numevt=$1 ;;
  -out) shift; out=$1 ;; 
  -b)  graphic=0 ;;
  -cylvtx)  igvx="VX 'vgparm.dat'" ;;
  -nump)  shift ; numpart=$1 ;;
  -help) helpmsg ; exit 0 ;;
  *) echo "Error :: Invalid option " $1 ; helpmsg ; exit ;;
 esac
 shift
done

echo "******** executing runmain on $HOSTNAME ************"
date
echo "Parameters of simulation are"
echo "optfull = $optfull"
echo "numevt = $numevt"
echo "output file = $out"
echo "graphic = $graphic"
echo "igvx = $igvx "
#
if [ $graphic -eq 1 ] ; then
    swopt=" 1 0 " 
    dbgopt="DEBU 1 $numevt 1 "
fi

#
#  GTYP = 1 ( 2 Tesla), =2 (3 Tesla)
# time $execfile <<EOF
$execfile <<EOF
LIST
$dbgopt
GTYP   2
DRAW 'graphic.dat'
C DEBU 1 3 1
SWIT  0  0  0 $swopt
$optfull
$igvx
TRIG $numevt
GEN  'FILE'
VECI 'jiminput.bnk' 
EVTO '$out'
VX   'vxparm.dat'
EOF

date

